apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: python-argocd-deployment
  namespace: argocd
spec: 
  project: default
  source: 
    repoURL: "https://github.com/PaulaCiocu/PythonProject"
    targetRevision: main 
    path: LibrarieProiect
  destination:
    namespace: auto-selfheal-demo
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
