apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-cd-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cd-deployment
  template:
    metadata:
      labels:
        app: cd-deployment
    spec:
      containers:
      - name: cd-deployment
        image: paula1907/my_python_tests:4
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "2000m"
            memory: "1024Mi"
          requests:
            cpu: '0.5'
            memory: 0.5Gi
        command: ["/bin/sh", "-c", "python3 test_1_project1.py; while true; do sleep 3600; done"]

     
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: python-cd-job
# spec:
#   template:
#     spec:
#       containers:
#       - name: python-cd-job
#         image: paula1907/my_python_tests:latest
#         command: ["python3", "test_1_project1.py"]
#       restartPolicy: Never
