FROM python:3.11-slim

RUN mkdir -p /app

WORKDIR /app

COPY LibrarieProiect/proiectFinal.py /app/
COPY LibrarieProiect/test2.txt /app/
COPY LibrarieProiect/test_1_project1.py /app/


CMD [ "python3", "test_1_project1.py"]



